showErrors
type 3 2 PREFIX/test.ts
type 4 2 PREFIX/test.ts
definition 3 2 PREFIX/test.ts
definition 4 2 PREFIX/test.ts
completions true 3 4 PREFIX/test.ts
completions true 4 4 PREFIX/test.ts
update 6 PREFIX/test.ts
var x = {a:1,b:2};
var s = "";
var a = [];
{s.to }
{x. }
{a. }
dump - PREFIX/test.ts
showErrors
completions true 4 4 PREFIX/test.ts
completions true 5 4 PREFIX/test.ts
completions true 6 4 PREFIX/test.ts
completions-brief true 6 4 PREFIX/test.ts
completions true 4 6 PREFIX/test.ts
